[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "hoxarix"
version = "0.1.2"
description = "Python SDK for Hoxarix AI Runtime Infrastructure"
readme = "README.md"

authors = [
    {name = "Hoxarix"}
]

license = {text = "Apache-2.0"}

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License"
]

keywords = [
    "ai",
    "agents",
    "runtime",
    "llm",
    "infrastructure"
]

requires-python = ">=3.10"

dependencies = [
    "requests>=2.31.0"
]


[tool.setuptools.packages.find]
where = ["."]
[project.urls]
Homepage = "https://hoxarix.com"
Repository = "https://github.com/mohammadnataj/hoxarix-python"

[tool.pytest.ini_options]
markers = [
    "integration: production runtime integration tests"
]
